# FILENAME: .github/workflows/ci.yml
name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Run ruff linter
        run: |
          uv run --group lint -p 3.12 ruff check .

      - name: Run ruff formatter check
        run: |
          uv run --group lint -p 3.12 ruff format --check .

  type-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7

    - name: Run type checking
      run: |
        uv run --group type-check -p 3.12 mypy src/qlass

  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7

    - name: Run tests and collect coverage
      run: |
        uv run --group test -p 3.12 pytest --cov --cov-report=xml
      env:
        # This disables Numba's JIT for accurate coverage reporting
        QLASS_DISABLE_JIT: 1

    - name: Upload coverage to Codecov
      if: github.event_name == 'pull_request'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: false
        verbose: true